"""M117c-final: layout-pack writable_zones runtime checker."""

from __future__ import annotations

from pathlib import Path

import pytest

from veles.core.layout.writable import is_writable, writable_zones
from veles.core.project import init_project, load_project


@pytest.fixture()
def isolated_home(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    monkeypatch.setenv("VELES_USER_HOME", str(tmp_path / "home"))
    return tmp_path / "home"


# ---- llm-wiki defaults (M189: permissive — declares no writable_zones) ----


def test_wiki_path_writable_under_llm_wiki(isolated_home: Path, tmp_path: Path) -> None:
    """`wiki/` stays writable under llm-wiki (it's project-root, permissive
    now covers it — this pins the specific path that matters most)."""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, "wiki/concepts/foo.md")
    assert is_writable(project, "wiki/queries/bar.md")


def test_sources_writable_under_llm_wiki(isolated_home: Path, tmp_path: Path) -> None:
    """M189: llm-wiki declares no writable_zones, so it is permissive —
    `sources/` is no longer hard-readonly (that discipline moved to the
    prompt/AGENTS.md convention, not the write-permission mechanism)."""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, "sources/raw_dump.txt")
    assert is_writable(project, "sources/subdir/file.md")


def test_veles_state_always_writable(isolated_home: Path, tmp_path: Path) -> None:
    """`.veles/` is always writable, even if the pack doesn't list it."""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, ".veles/memory.db")
    assert is_writable(project, ".veles/tmp/clipboard.txt")
    assert is_writable(project, ".veles/skills/my_skill/SKILL.md")


def test_arbitrary_root_file_writable_under_llm_wiki(isolated_home: Path, tmp_path: Path) -> None:
    """M189: llm-wiki declares no zones, so files in the project root
    outside `wiki/`/`sources/` are writable too (permissive by design —
    e.g. relocating an arbitrary project file during a migration)."""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, "README.md")
    assert is_writable(project, "src/main.py")
    assert is_writable(project, "notes/foo.md")


# ---- AGENTS.md is always writable (Veles generates it for every layout) ----


def test_agents_md_writable_under_llm_wiki(isolated_home: Path, tmp_path: Path) -> None:
    """AGENTS.md is generated by `apply_scaffold` for every layout, so the
    agent may edit it like any other file it generated. (Under llm-wiki
    this is now moot for write purposes — the pack is fully permissive
    since M189 — but AGENTS.md must stay always-writable for packs that
    DO restrict, so we keep pinning it here too.)"""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, "AGENTS.md")


def test_agents_md_writable_under_notes(isolated_home: Path, tmp_path: Path) -> None:
    """Same under the notes pack (only `notes/` is a declared zone)."""
    project = init_project(tmp_path / "proj", name="proj", layout="notes")
    assert is_writable(project, "AGENTS.md")
    # The notes zone still applies; a sibling root file does not.
    assert is_writable(project, "notes/a.md")
    assert not is_writable(project, "README.md")


def test_agents_md_exact_match_not_prefix(isolated_home: Path, tmp_path: Path) -> None:
    """Only AGENTS.md itself — not lookalikes — is always-writable. The
    exact-match check must not regress to the loose prefix matching used
    for directory zones. Uses `notes` (a pack that still declares zones —
    llm-wiki is permissive since M189, so it wouldn't exercise this)."""
    project = init_project(tmp_path / "proj", name="proj", layout="notes")
    assert not is_writable(project, "AGENTS.md.bak")
    assert not is_writable(project, "AGENTS.markdown")
    assert not is_writable(project, "wiki-AGENTS.md")


# ---- permissive fallback ----


def test_unknown_layout_permissive(isolated_home: Path, tmp_path: Path) -> None:
    """When the layout-pack doesn't resolve, fall back to permissive
    (anything inside the project root is writable). Preserves the
    pre-M117 contract."""
    project = init_project(tmp_path / "proj", name="proj")
    toml_path = project.project_toml_path
    text = toml_path.read_text(encoding="utf-8")
    toml_path.write_text(
        text.replace('layout = "llm-wiki"', 'layout = "ghost-pack"'),
        encoding="utf-8",
    )
    reloaded = load_project(project.root)
    assert is_writable(reloaded, "README.md")
    assert is_writable(reloaded, "src/main.py")
    # .veles/ still writable in permissive mode
    assert is_writable(reloaded, ".veles/memory.db")


# ---- outside the project tree ----


def test_outside_project_root_not_writable(isolated_home: Path, tmp_path: Path) -> None:
    """Defence in depth — path_guard catches it earlier, but is_writable
    also says no when the path resolves outside the project root."""
    project = init_project(tmp_path / "proj", name="proj")
    outside = (tmp_path / "elsewhere" / "file.txt").resolve()
    outside.parent.mkdir(parents=True, exist_ok=True)
    assert not is_writable(project, str(outside))


# ---- writable_zones diagnostic ----


def test_writable_zones_llm_wiki_is_just_defaults(isolated_home: Path, tmp_path: Path) -> None:
    """M189: llm-wiki declares no writable_zones, so the diagnostic surface
    only lists the always-on defaults — the pack itself contributes
    nothing (it's permissive, not zone-restricted)."""
    project = init_project(tmp_path / "proj", name="proj")
    zones = writable_zones(project)
    assert any(".veles" in z for z in zones)
    assert "AGENTS.md" in zones
    # No pack-declared zone — llm-wiki declares none.
    assert not any(z.rstrip("/") == "wiki" for z in zones)
    assert not any(z.rstrip("/") == "sources" for z in zones)


def test_writable_zones_permissive_when_no_pack(isolated_home: Path, tmp_path: Path) -> None:
    """No pack resolves → writable_zones returns just the always-on
    defaults (callers know to treat empty pack list as permissive)."""
    project = init_project(tmp_path / "proj", name="proj")
    toml_path = project.project_toml_path
    toml_path.write_text(
        toml_path.read_text(encoding="utf-8").replace(
            'layout = "llm-wiki"', 'layout = "ghost-pack"'
        ),
        encoding="utf-8",
    )
    reloaded = load_project(project.root)
    zones = writable_zones(reloaded)
    # Just the always-writable defaults
    assert any(".veles" in z for z in zones)
    assert not any("wiki" in z for z in zones)


# ---- path normalisation ----


def test_absolute_path_inside_project_writable(isolated_home: Path, tmp_path: Path) -> None:
    project = init_project(tmp_path / "proj", name="proj")
    abs_wiki = project.root / "wiki" / "x.md"
    assert is_writable(project, str(abs_wiki))


def test_dotdot_resolved_against_project_root(isolated_home: Path, tmp_path: Path) -> None:
    """`wiki/../sources/foo` resolves to `sources/foo` — writable under the
    now-permissive llm-wiki (M189); still resolved relative to the project
    root either way."""
    project = init_project(tmp_path / "proj", name="proj")
    assert is_writable(project, "wiki/../sources/foo.txt")


# ---- M189: universal opt-in contract — locked with dedicated tests ----


def _write_pack(root: Path, name: str, body: str) -> None:
    pack_dir = root / "layouts" / name
    pack_dir.mkdir(parents=True, exist_ok=True)
    (pack_dir / "layout.toml").write_text(body, encoding="utf-8")


def test_no_declared_zones_is_permissive_anywhere_in_project(
    isolated_home: Path, tmp_path: Path
) -> None:
    """Contract anchor: a pack that declares NO writable_zones imposes no
    write restriction at all — arbitrary in-project paths are writable.
    Uses the builtin `bare` pack, which ships with no writable_zones."""
    project = init_project(tmp_path / "proj", name="proj", layout="bare")
    assert is_writable(project, "anywhere/foo.md")
    assert is_writable(project, "deeply/nested/path/bar.txt")
    assert is_writable(project, "top-level.txt")
    # The "only path_guard's project-boundary applies outside" half of the
    # contract — is_writable itself also refuses outside-root paths
    # (defence in depth; path_guard is the primary gate for that).
    outside = (tmp_path / "elsewhere" / "file.txt").resolve()
    outside.parent.mkdir(parents=True, exist_ok=True)
    assert not is_writable(project, str(outside))


def test_declared_zones_still_enforced_by_custom_pack(isolated_home: Path, tmp_path: Path) -> None:
    """Mechanism-preserved proof: a layout that OPTS IN by declaring zones
    is still restricted to them — `llm-wiki` going permissive does not
    weaken the universal mechanism for packs that declare zones."""
    _write_pack(
        isolated_home / ".veles",
        "custom-restricted",
        '[layout]\nname = "custom-restricted"\n'
        '[[layout.writable_zones]]\npath = "wiki/"\n'
        '[[layout.writable_zones]]\npath = "sources/"\nreadonly = true\n',
    )
    project = init_project(tmp_path / "proj", name="proj", layout="custom-restricted")
    assert is_writable(project, "wiki/x.md")
    assert not is_writable(project, "sources/x.md")
    # Anything outside the declared zones is refused too — the pack opted
    # into a restriction, not just a readonly carve-out.
    assert not is_writable(project, "random.txt")


def test_relocation_allowed_under_llm_wiki(isolated_home: Path, tmp_path: Path) -> None:
    """`guard_write` (the chokepoint `move_file` calls on both endpoints)
    no longer refuses relocating an arbitrary project file into `wiki/`
    or `sources/` under the now-permissive llm-wiki pack."""
    from veles.core.tools.builtin._fs_write_guard import guard_write

    project = init_project(tmp_path / "proj", name="proj")
    src = project.root / "misc" / "raw.txt"
    src.parent.mkdir(parents=True, exist_ok=True)
    src.write_text("raw", encoding="utf-8")

    into_wiki = project.root / "wiki" / "concepts" / "raw.md"
    into_sources = project.root / "sources" / "raw.txt"

    assert guard_write(src, project) is None
    assert guard_write(into_wiki, project) is None
    assert guard_write(into_sources, project) is None
