"""M117c-final / M189: `writable_zones` is a UNIVERSAL, OPT-IN, layout-level
write-permission mechanism.

**The contract:**
- A layout pack MAY declare zones with permissions in `layout.toml`
  (`[[layout.writable_zones]]` — `path` + optional `readonly = true`).
- **A layout that declares NO zones has NO write restriction**: the agent
  may write anywhere inside the project root. Only `path_guard`'s
  project-boundary + `..`/symlink rules still apply (reads stay
  project-wide regardless — this module gates WRITES only, never reads).
- A layout that DOES declare zones is restricted to them: writable zones
  are allow-listed, `readonly = true` zones are hard-refused, and anything
  outside all declared zones is refused too.
- The builtin `llm-wiki` pack declares no zones (M189) — it is permissive
  by design; the sources/wiki discipline is a *prompt* convention, not an
  enforced write boundary. Packs that want a hard boundary (e.g. a custom
  pack keeping `sources/` immutable) opt in by declaring zones themselves;
  the mechanism below is unchanged and still enforces them.

`is_writable(project, path)` is the runtime check the builtin
`write_file` tool (and any agent-generated write tool) consults
before persisting bytes, via `fs_write_guard.guard_write` — the single
chokepoint every builtin write/move/delete tool calls. The read sandbox
(`path_guard.py`) stays unchanged — read remains full-project.

Always-writable zones, regardless of pack (even a pack that declares
zones and would otherwise refuse these):
- `<cwd>/.veles/{skills,tools,tmp,plans,memory,artifacts}/` — the agent's
  own skills, tools and scratch space (`AGENT_WRITABLE_STATE`). The rest of
  `.veles/` (trust.json, config.toml, modules/, memory.db, …) is Veles'
  state and always refused (`is_veles_managed`), whatever the pack says —
  as is any nested `.veles/`. Auto-executed files and agent CLI config
  (`.git/`, `.claude/`, `.envrc`, … — `needs_confirmation`) are writable only
  after a hard confirmation.
- `AGENTS.md`     — the project's context file. Veles generates it for
  every layout (`scaffold.apply_scaffold`), so the agent may edit it
  like any other file it generated, no matter how restrictive the pack's
  declared zones are. Matched exactly (not as a prefix) so lookalikes
  like `AGENTS.md.bak` stay outside the write surface.

Layout-pack-declared writable zones come from the active pack's
manifest (`find_layout(project.layout_name)`) via the
`writable_path_strings()` helper that already filters out readonly
zones.

When no pack is active (custom layout that didn't ship a layout.toml,
or the project's `layout_name` points at a missing pack) — or when the
active pack simply declares no zones at all — fall back to permissive
mode: allow everything inside the project root. This is the SAME
"no zones ⇒ unrestricted" contract stated above, just reached via a
different route (no pack resolves, vs. a pack resolves but is empty).
"""

from __future__ import annotations

import configparser
import logging
import os
import subprocess
import unicodedata
from dataclasses import dataclass
from pathlib import Path

from veles.core.delegate_dir import DIR_PREFIX as _DELEGATE_PREFIX
from veles.core.path_guard import is_inside
from veles.core.project import Project
from veles.core.user_paths import user_home

logger = logging.getLogger(__name__)


# The only subdirs of the project's `.veles/` the agent's file tools may write:
# its own skills, tools, scratch, plans, memory notes and artifacts. They are
# writable no matter what the layout pack declares. Everything else there —
# trust.json, config.toml, project.toml, modules/, memory.db, any new file — is
# Veles' own state: writing it would let the agent grant itself tools or load
# code, so Veles changes it only through its own commands and core APIs.
AGENT_WRITABLE_STATE: tuple[str, ...] = ("skills", "tools", "tmp", "plans", "memory", "artifacts")

# Exact-match files that are always writable regardless of pack. Unlike
# the directory prefixes above these are matched by full equality, so
# `AGENTS.md` is writable but `AGENTS.md.bak` / `AGENTS.markdown` are not.
# AGENTS.md is generated by `scaffold.apply_scaffold` for every layout, so
# the agent edits it like any other file it generated.
_ALWAYS_WRITABLE_FILES: tuple[str, ...] = ("AGENTS.md",)

# Tier 1 — never writable by the agent's file tools, at any depth in the project
# (the active `.veles/` alone keeps its `AGENT_WRITABLE_STATE`): another Veles
# state dir — run veles there and it loads the planted trust and modules.
# Compared NFC + casefolded, like every name below.
_MANAGED_NAMES = frozenset({".veles"})

# Tier 2 — writable only after a hard confirmation (`confirm_critical`: no trust
# grant or autopilot covers it, no human means no): files that run without an
# explicit command (git hooks incl. the `.githooks`/pre-commit/lefthook
# conventions, `.envrc`, editor tasks, dev containers) and the config of agent
# CLIs (hooks, permissions, MCP servers they run outside Veles' trust ladder).
# Matched as any path component, at any depth; `needs_confirmation` also covers
# where a symlinked root entry points and the repo's `core.hooksPath`.
_CONFIRM_NAMES = frozenset(
    {
        ".git",
        ".githooks",
        ".pre-commit-config.yaml",
        "lefthook.yml",
        "lefthook.yaml",
        ".lefthook.yml",
        ".lefthook.yaml",
        ".claude",
        ".gemini",
        ".agents",  # agy reads a workspace's MCP servers from .agents/mcp_config.json
        ".codex",
        ".vscode",
        ".devcontainer",
        ".husky",
        ".envrc",
        ".mcp.json",
    }
)


def _folded(name: str) -> str:
    return unicodedata.normalize("NFC", name).casefold()


def is_writable(project: Project, path: str | Path) -> bool:
    """True iff the agent may write to `path` under `project`'s active
    layout-pack. Always-writable zones (`AGENT_WRITABLE_STATE` under `.veles/`,
    `AGENTS.md`) override the pack's declaration; the rest of `.veles/` is
    always refused.

    Otherwise this is a **universal, opt-in** contract: if the active
    pack declares `writable_zones` in its `layout.toml`, `path` must fall
    inside a non-readonly declared zone. If the pack declares NO zones
    at all — as `bare` and `llm-wiki` — there is no restriction and every
    in-project path is writable. A pack that isn't installed fails closed
    (only the always-writable paths), except the layouts that moved to the
    registry, whose zones are known. Gates writes only; reads stay
    project-wide via `path_guard` regardless of this check.

    `path` is normalised relative to `project.root`. Absolute paths
    outside the project root are rejected (those should never reach
    here — `path_guard` catches them first).
    """
    abs_path = (project.root / path).resolve()
    try:
        rel = abs_path.relative_to(project.root.resolve())
    except ValueError:
        # Outside the project root — `path_guard` is the gate for
        # that. We say no here too for defence in depth.
        return False
    in_state = _state_verdict(project, abs_path)
    if in_state is not None:
        return in_state
    rel_str = str(rel)
    # Normalise to forward slashes for the prefix check; Path's
    # `as_posix` does that without affecting filesystem behaviour.
    rel_posix = rel.as_posix() + ("/" if abs_path.is_dir() else "")

    # Exact-match always-writable files (e.g. AGENTS.md). Compare the
    # slash-free posix form so a same-named directory wouldn't sneak in.
    if rel.as_posix() in _ALWAYS_WRITABLE_FILES:
        return True

    zones = _effective_writable_zones(project)
    if not zones:
        # Contract anchor (M189): a layout that declares NO writable_zones
        # is UNRESTRICTED — every path inside the project root is writable
        # (e.g. bare, llm-wiki). A pack that doesn't resolve fails closed.
        return True
    for zone in zones:
        # Zone may be `wiki/` or `wiki` — match both forms.
        zone_norm = zone.rstrip("/")
        if rel_posix.startswith(zone_norm + "/") or rel_str == zone_norm:
            return True
    return False


def writable_zones(project: Project) -> tuple[str, ...]:
    """Return the effective writable zones for `project` — the layout
    pack's declared zones plus the always-writable defaults. Used by
    diagnostic surfaces (`veles doctor`, `/status` slash) so the
    user can see what the agent can touch."""
    pack_zones = _effective_writable_zones(project)
    state = project.state_dir.name
    return (
        tuple(f"{state}/{name}/" for name in AGENT_WRITABLE_STATE)
        + _ALWAYS_WRITABLE_FILES
        + tuple(z if z.endswith("/") else z + "/" for z in pack_zones if z not in _NOTHING)
    )


def is_veles_managed(project: Project, path: str | Path) -> bool:
    """True iff `path` is Veles-managed, closed to the agent's file tools: the
    project's `.veles/` outside `AGENT_WRITABLE_STATE`, or any path through a
    nested `.veles/`."""
    return _state_verdict(project, (project.root / path).resolve()) is False


def needs_confirmation(project: Project, path: str | Path) -> bool:
    """True iff a write to `path` needs a hard confirmation: a component of its
    in-project path is one of `_CONFIRM_NAMES` (`.git/`, `.claude/`, `.envrc`, …),
    or it lies under what a symlinked root entry or `core.hooksPath` points at."""
    abs_path = (project.root / path).resolve()
    try:
        parts = abs_path.relative_to(project.root.resolve()).parts
    except ValueError:
        return False
    if any(_folded(part) in _CONFIRM_NAMES for part in parts):
        return True
    return any(is_inside(abs_path, target, fold=True) for target in _protected_targets(project))


def _protected_targets(project: Project) -> list[Path]:
    """Where a root-level protected entry that is a symlink really points (the
    guard sees resolved paths, so `.git -> gitdata` would hide `gitdata/hooks`),
    plus the hooks dir git actually uses (`core.hooksPath` from any config level,
    an enclosing repo, a `.git` file) and the one the project's own `.git/config`
    names — both, since git may be missing or may answer for an enclosing repo
    while the project's config is broken. An unreadable config adds nothing."""
    out = [
        (project.root / name).resolve()
        for name in _CONFIRM_NAMES
        if (project.root / name).is_symlink()
    ]
    hooks_dir = _git_hooks_dir(project.root)
    if hooks_dir is not None:
        out.append(hooks_dir)
    # Git's config is INI-like: keys may lack a value, values may be quoted and
    # carry a trailing `;`/`#` comment. A value that can't be resolved (unknown
    # `~user`, a NUL) adds nothing — it must never make the write guard throw.
    parser = configparser.ConfigParser(
        strict=False, interpolation=None, allow_no_value=True, inline_comment_prefixes=("#", ";")
    )
    try:
        parser.read_string((project.root / ".git" / "config").read_text(encoding="utf-8"))
        hooks = (parser.get("core", "hooksPath", fallback="") or "").strip().strip('"')
        if hooks:
            out.append((project.root / Path(hooks).expanduser()).resolve())
    except (OSError, UnicodeDecodeError, configparser.Error, RuntimeError, ValueError):
        pass
    return out


def _git_hooks_dir(root: Path) -> Path | None:
    """`git rev-parse --git-path hooks` from `root`: the hooks dir with every config
    level applied. None when git is missing, slow, or `root` is not in a repo
    (dubious ownership included) — the caller falls back to parsing the config.
    `rev-parse` reads no index and runs no hooks or fsmonitor."""
    try:
        run = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "--git-path", "hooks"],
            capture_output=True,
            text=True,
            timeout=2,
            check=False,
        )
    except (OSError, subprocess.SubprocessError, ValueError):
        return None
    out = run.stdout.strip()
    if run.returncode != 0 or not out:
        return None
    try:
        return (root / Path(out).expanduser()).resolve()
    except (OSError, RuntimeError, ValueError):
        return None


# Files under $HOME that run without an explicit command, and the agent CLIs' config:
# closed for run_shell (release F). `~/.veles` (approvals, trust, user modules) is added
# from `user_home()`.
_HOME_AUTORUN: tuple[str, ...] = (
    ".bashrc",
    ".bash_profile",
    ".bash_login",
    ".profile",
    ".zshrc",
    ".zprofile",
    ".zshenv",
    ".zlogin",
    ".config/fish",
    ".ssh",
    ".gitconfig",
    ".config/git",
    "Library/LaunchAgents",
    ".config/autostart",
    ".config/systemd/user",
    ".claude",
    ".claude.json",
    ".codex",
    ".gemini",
)
# Where git runs code from, at any depth (objects, refs and the index stay writable).
_GIT_CODE: tuple[str, ...] = (".git/hooks", ".git/config", ".git/config.worktree")


@dataclass(frozen=True, slots=True)
class ShellGuard:
    """What the agent's `run_shell` may not write (`core/sandbox.py` enforces it): the
    paths the file tools refuse or hard-confirm, plus the user's own auto-run files.
    Canonical paths — a sandbox profile with a symlinked path protects nothing."""

    root: Path | None
    readonly: tuple[Path, ...]
    readonly_names: tuple[str, ...]
    holes: tuple[Path, ...]
    relock_prefix: Path | None
    pinned: tuple[Path, ...]


def shell_guard(project: Project | None) -> ShellGuard:
    home = Path.home()
    paths: list[Path] = [user_home(), *(home / rel for rel in _HOME_AUTORUN)]
    if project is None:
        return ShellGuard(None, _canonical(paths), (), (), None, ())
    root = Path(os.path.realpath(project.root))
    git = root / ".git"
    paths += [root / rel for rel in _GIT_CODE]
    paths += [*sorted(git.glob("modules/*/hooks")), *sorted(git.glob("modules/*/config"))]
    paths += [root / name for name in sorted(_CONFIRM_NAMES - {".git"})]
    paths += _protected_targets(project)
    paths.append(project.state_dir)
    state = Path(os.path.realpath(project.state_dir))
    holes = [state / n for n in AGENT_WRITABLE_STATE if not (project.state_dir / n).is_symlink()]
    names = tuple(sorted((_CONFIRM_NAMES - {".git"}) | _MANAGED_NAMES)) + _GIT_CODE
    return ShellGuard(
        root=root,
        readonly=_canonical(paths),
        readonly_names=names,
        holes=tuple(holes),
        relock_prefix=state / "tmp" / _DELEGATE_PREFIX,
        pinned=(root, Path(os.path.realpath(git))),
    )


def _canonical(paths: list[Path]) -> tuple[Path, ...]:
    """`realpath` of each (a missing tail stays as written), plus the path as written
    when it is a symlink — replacing the link must be refused too. Order kept, no dups."""
    out: dict[Path, None] = {}
    for p in paths:
        absolute = Path(os.path.abspath(p))
        out[Path(os.path.realpath(absolute))] = None
        if absolute.is_symlink():
            out[absolute] = None
    return tuple(out)


def _state_verdict(project: Project, abs_path: Path) -> bool | None:
    """None outside Veles-managed paths; inside the project's `.veles/`, whether
    the agent may write there. Decided by file identity (`is_inside`), not
    spelling, so `.VELES/trust.json` on a case-insensitive FS is still
    trust.json. The refusing side folds a missing tail; the allowing side
    compares it exactly, so folding never widens the allow-list. An allow-listed
    name that is a symlink does not count: `.veles/tmp -> .veles` (or -> the
    root) would otherwise open all of `.veles/`, and any link can be retargeted
    after the check.

    Any other path component named in `_MANAGED_NAMES` (a nested `sub/.veles/`)
    is refused outright: Veles loads the nearest `.veles/project.toml` with its
    trust and modules."""
    state = project.state_dir
    in_state = is_inside(abs_path, state, fold=True)
    try:
        parts = abs_path.relative_to(project.root.resolve()).parts
    except ValueError:
        parts = ()
    # The active state dir's own first component keeps its allow-list below.
    if any(_folded(part) in _MANAGED_NAMES for part in parts[1 if in_state else 0 :]):
        return False
    if not in_state:
        return None
    # A CLI delegate's run files (`.veles/tmp/delegate-<pid>/`): claude runs whatever its
    # --mcp-config names, and the MCP child trusts the budget there.
    delegate = len(parts) > 2 and _folded(parts[1]) == "tmp"
    if delegate and _folded(parts[2]).startswith(_DELEGATE_PREFIX):
        return False
    return any(
        is_inside(abs_path, state / name, fold=False)
        for name in AGENT_WRITABLE_STATE
        if not (state / name).is_symlink()
    )


# The zones of the layouts that moved to the registry, for a project whose pack
# isn't reinstalled yet (`llm-wiki` declares none — it stays permissive).
_MIGRATED_LAYOUT_ZONES: dict[str, list[str]] = {"llm-wiki": [], "notes": ["notes/"]}
# A pack that doesn't resolve may have declared zones we can't see: fail closed.
_NOTHING = ["\0"]


def _effective_writable_zones(project: Project) -> list[str]:
    """Writable zones of the active layout-pack; empty when the pack declares
    none (unrestricted). A pack that doesn't resolve yields a zone nothing
    matches, so only the always-writable paths stay open."""
    try:
        from veles.core.layout.discovery import find_layout

        pack = find_layout(project.layout_name, project=project)
    except Exception as exc:
        logger.debug("layout lookup failed: %s", exc)
        pack = None
    if pack is None:
        return list(_MIGRATED_LAYOUT_ZONES.get(project.layout_name, _NOTHING))
    return list(pack.manifest.writable_path_strings())


__all__ = [
    "AGENT_WRITABLE_STATE",
    "ShellGuard",
    "is_veles_managed",
    "is_writable",
    "shell_guard",
    "writable_zones",
]
