"""M117c-final / M189: `writable_zones` is a UNIVERSAL, OPT-IN, layout-level
write-permission mechanism.

**The contract:**
- A layout pack MAY declare zones with permissions in `layout.toml`
  (`[[layout.writable_zones]]` — `path` + optional `readonly = true`).
- **A layout that declares NO zones has NO write restriction**: the agent
  may write anywhere inside the project root. Only `path_guard`'s
  project-boundary + `..`/symlink rules still apply (reads stay
  project-wide regardless — this module gates WRITES only, never reads).
- A layout that DOES declare zones is restricted to them: writable zones
  are allow-listed, `readonly = true` zones are hard-refused, and anything
  outside all declared zones is refused too.
- The builtin `llm-wiki` pack declares no zones (M189) — it is permissive
  by design; the sources/wiki discipline is a *prompt* convention, not an
  enforced write boundary. Packs that want a hard boundary (e.g. a custom
  pack keeping `sources/` immutable) opt in by declaring zones themselves;
  the mechanism below is unchanged and still enforces them.

`is_writable(project, path)` is the runtime check the builtin
`write_file` tool (and any agent-generated write tool) consults
before persisting bytes, via `fs_write_guard.guard_write` — the single
chokepoint every builtin write/move/delete tool calls. The read sandbox
(`path_guard.py`) stays unchanged — read remains full-project.

Always-writable zones, regardless of pack (even a pack that declares
zones and would otherwise refuse these):
- `<cwd>/.veles/{skills,tools,tmp,plans,memory,artifacts}/` — the agent's
  own skills, tools and scratch space (`AGENT_WRITABLE_STATE`). The rest of
  `.veles/` (trust.json, config.toml, modules/, memory.db, …) is Veles'
  state and always refused (`is_veles_managed`), whatever the pack says.
- `AGENTS.md`     — the project's context file. Veles generates it for
  every layout (`scaffold.apply_scaffold`), so the agent may edit it
  like any other file it generated, no matter how restrictive the pack's
  declared zones are. Matched exactly (not as a prefix) so lookalikes
  like `AGENTS.md.bak` stay outside the write surface.

Layout-pack-declared writable zones come from the active pack's
manifest (`find_layout(project.layout_name)`) via the
`writable_path_strings()` helper that already filters out readonly
zones.

When no pack is active (custom layout that didn't ship a layout.toml,
or the project's `layout_name` points at a missing pack) — or when the
active pack simply declares no zones at all — fall back to permissive
mode: allow everything inside the project root. This is the SAME
"no zones ⇒ unrestricted" contract stated above, just reached via a
different route (no pack resolves, vs. a pack resolves but is empty).
"""

from __future__ import annotations

import logging
from pathlib import Path

from veles.core.path_guard import is_inside
from veles.core.project import Project

logger = logging.getLogger(__name__)


# The only subdirs of the project's `.veles/` the agent's file tools may write:
# its own skills, tools, scratch, plans, memory notes and artifacts. They are
# writable no matter what the layout pack declares. Everything else there —
# trust.json, config.toml, project.toml, modules/, memory.db, any new file — is
# Veles' own state: writing it would let the agent grant itself tools or load
# code, so Veles changes it only through its own commands and core APIs.
AGENT_WRITABLE_STATE: tuple[str, ...] = ("skills", "tools", "tmp", "plans", "memory", "artifacts")

# Exact-match files that are always writable regardless of pack. Unlike
# the directory prefixes above these are matched by full equality, so
# `AGENTS.md` is writable but `AGENTS.md.bak` / `AGENTS.markdown` are not.
# AGENTS.md is generated by `scaffold.apply_scaffold` for every layout, so
# the agent edits it like any other file it generated.
_ALWAYS_WRITABLE_FILES: tuple[str, ...] = ("AGENTS.md",)


def is_writable(project: Project, path: str | Path) -> bool:
    """True iff the agent may write to `path` under `project`'s active
    layout-pack. Always-writable zones (`AGENT_WRITABLE_STATE` under `.veles/`,
    `AGENTS.md`) override the pack's declaration; the rest of `.veles/` is
    always refused.

    Otherwise this is a **universal, opt-in** contract: if the active
    pack declares `writable_zones` in its `layout.toml`, `path` must fall
    inside a non-readonly declared zone. If the pack declares NO zones
    at all — as `llm-wiki` does since M189 — there is no restriction and
    every in-project path is writable. Gates writes only; reads stay
    project-wide via `path_guard` regardless of this check.

    `path` is normalised relative to `project.root`. Absolute paths
    outside the project root are rejected (those should never reach
    here — `path_guard` catches them first).
    """
    abs_path = (project.root / path).resolve()
    try:
        rel = abs_path.relative_to(project.root.resolve())
    except ValueError:
        # Outside the project root — `path_guard` is the gate for
        # that. We say no here too for defence in depth.
        return False
    in_state = _state_verdict(project, abs_path)
    if in_state is not None:
        return in_state
    rel_str = str(rel)
    # Normalise to forward slashes for the prefix check; Path's
    # `as_posix` does that without affecting filesystem behaviour.
    rel_posix = rel.as_posix() + ("/" if abs_path.is_dir() else "")

    # Exact-match always-writable files (e.g. AGENTS.md). Compare the
    # slash-free posix form so a same-named directory wouldn't sneak in.
    if rel.as_posix() in _ALWAYS_WRITABLE_FILES:
        return True

    zones = _effective_writable_zones(project)
    if not zones:
        # Contract anchor (M189): a layout that declares NO writable_zones
        # is UNRESTRICTED — every path inside the project root is writable.
        # This covers both "no pack resolves" and "pack resolves but its
        # manifest declares zero writable_zones" (e.g. llm-wiki, bare).
        return True
    for zone in zones:
        # Zone may be `wiki/` or `wiki` — match both forms.
        zone_norm = zone.rstrip("/")
        if rel_posix.startswith(zone_norm + "/") or rel_str == zone_norm:
            return True
    return False


def writable_zones(project: Project) -> tuple[str, ...]:
    """Return the effective writable zones for `project` — the layout
    pack's declared zones plus the always-writable defaults. Used by
    diagnostic surfaces (`veles doctor`, `/status` slash) so the
    user can see what the agent can touch."""
    pack_zones = _effective_writable_zones(project)
    state = project.state_dir.name
    return (
        tuple(f"{state}/{name}/" for name in AGENT_WRITABLE_STATE)
        + _ALWAYS_WRITABLE_FILES
        + tuple(z if z.endswith("/") else z + "/" for z in pack_zones)
    )


def is_veles_managed(project: Project, path: str | Path) -> bool:
    """True iff `path` is inside the project's `.veles/` but outside
    `AGENT_WRITABLE_STATE` — Veles' own state, closed to the agent's file tools."""
    return _state_verdict(project, (project.root / path).resolve()) is False


def _state_verdict(project: Project, abs_path: Path) -> bool | None:
    """None outside `.veles/`; inside it, whether the agent may write there.
    Decided by file identity (`is_inside`), not spelling, so `.VELES/trust.json`
    on a case-insensitive FS is still trust.json. The refusing side folds a
    missing tail; the allowing side compares it exactly, so folding never
    widens the allow-list. An allow-listed name that is a symlink does not count:
    `.veles/tmp -> .veles` (or -> the root) would otherwise open all of
    `.veles/`, and any link can be retargeted after the check."""
    state = project.state_dir
    if not is_inside(abs_path, state, fold=True):
        return None
    return any(
        is_inside(abs_path, state / name, fold=False)
        for name in AGENT_WRITABLE_STATE
        if not (state / name).is_symlink()
    )


def _effective_writable_zones(project: Project) -> list[str]:
    """Pull writable zones from the active layout-pack. Empty list
    when no pack resolves or the pack declares no zones."""
    try:
        from veles.core.layout.discovery import find_layout

        pack = find_layout(project.layout_name, project=project)
    except Exception as exc:
        logger.debug("layout lookup failed: %s", exc)
        return []
    if pack is None:
        return []
    return list(pack.manifest.writable_path_strings())


__all__ = ["AGENT_WRITABLE_STATE", "is_veles_managed", "is_writable", "writable_zones"]
